version: '3'

services:
  postgresDB:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mamedov00
      - POSTGRES_DB=telegram_bot_system
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - TelegramWallet
  pgAdmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mamedov_99b@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=0000
    networks:
      - TelegramWallet
networks:
  TelegramWallet:
    driver: bridge