version: '3.7'

services:
  postgresDB:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=tgdb
    ports:
      - "5433:5433"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - TelegramWallet
  pgAdmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mamedov_99b@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=0000
    ports:
      - "5050:80"
    networks:
      - TelegramWallet
networks:
  TelegramWallet:
    driver: bridge