version: "3.9"

services:
  postgres:
    container_name: tg_db
    image: postgres:13.3
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root0000"
      POSTGRES_DB: "tgdb"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - TelegramWallet
  pgAdmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "mamedov_99b@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "root0000"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - TelegramWallet
networks:
  TelegramWallet:
    driver: bridge