version: '3'

services:
  bot_main:
      build:
        context: bot_main/
        dockerfile: Dockerfile
      container_name: bot_main
      entrypoint: python app.py
      env_file:
        - ./.env
      networks:
        - telegram_wallet_bot
      logging:
        options:
          max-size: 100m
  bot_alert:
    build:
      context: bot_alert/
      dockerfile: Dockerfile
    container_name: bot_alert
    command: uvicorn app:app --host 0.0.0.0 --port 7000
    env_file:
      - ./.env
    ports:
      - "83:7000"
    expose:
      - 83
    networks:
      - telegram_wallet_bot
    volumes:
      - ./src/files:/home/app/files
    logging:
      options:
        max-size: 100m

networks:
  telegram_wallet_bot:
    driver: bridge