version: '3'

services:
  sender_messages:
    build:
      context: sender_messages/
      dockerfile: Dockerfile
    container_name: sender_messages
    command: /usr/bin/supervisord
    restart: always
    env_file:
      - ./.env
    networks:
      - telegram_wallet_services
    logging:
      options:
        max-size: 100m
  checker_system:
    build:
      context: checker_system/
      dockerfile: Dockerfile
    container_name: checker_system
    command: /usr/bin/supervisord
    restart: always
    env_file:
      - ./.env
    networks:
      - telegram_wallet_services
    logging:
      options:
        max-size: 100m
  balancer:
    build:
      context: balancer/
      dockerfile: Dockerfile
    container_name: sender_messages
    command: /usr/bin/supervisord
    restart: always
    env_file:
      - ./.env
    networks:
      - telegram_wallet_services
    logging:
      options:
        max-size: 100m

  redis:
    container_name: service_redis
    image: "bitnami/redis:5.0.4"
    restart: always
    environment:
      - REDIS_PASSWORD=password0000
    ports:
      - "6379:6379"
    volumes:
      - "./prod_data/redis_data:/bitnami/redis/data"
    networks:
      - telegram_wallet_services
    logging:
      options:
        max-size: 100m

  balancer_worker:
    restart: always
    container_name: balancer_worker
    build:
      context: balancer/
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - ./.env
    command: celery --app worker.celery_worker worker -l info -Q balancer-queue -c 1
    networks:
      - telegram_wallet_services
    logging:
      options:
        max-size: 100m
  sender_message_worker:
    restart: always
    container_name: sender_message_worker
    build:
      context: sender_messages/
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - ./.env
    command: celery --app worker.celery_worker worker -l info -Q sender-queu -c 1
    networks:
      - telegram_wallet_services
    logging:
      options:
        max-size: 100m
networks:
  telegram_wallet_services:
    driver: bridge