version: "3.9"

services:
  database_interface:
    build:
      context: .
      dockerfile: Dockerfile
    command: python ./manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    networks:
      - database_interface

  database:
    container_name: database
    image: postgres:13.3
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    networks:
      - database_interface
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d telegram_bot_wallet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:5.7
    env_file:
      - .env.dev
    ports:
      - "5050:80"
    restart: always
    networks:
      - database_interface
networks:
  database_interface:
    driver: bridge
