version: '3'

services:
  admin_site:
    build:
      context: admin_site/
      dockerfile: Dockerfile
    container_name: admin_site
    command: python app.py
    env_file:
      - ./.env
    ports:
      - "80:8000"
    expose:
      - 85
    networks:
      - telegram_wallet_admin
    logging:
      options:
        max-size: 100m

  admin_bot:
    build:
      context: admin_bot/
      dockerfile: Dockerfile
    container_name: admin_bot
    entrypoint: python app.py
    env_file:
      - ./.env
    networks:
      - telegram_wallet_admin
    logging:
      options:
        max-size: 100m


networks:
  telegram_wallet_admin:
    driver: bridge